### PR TITLE
Home page and Demo page aesthetic

### PR DESCRIPTION
**Pull request by deborahsrcho**
- removed extra buttons on demo page
- made demo page more aesthetic and colorful
- added navigation bars to home and demo pages

### CODE REVIEW

**Comment by xorbit3024** [comment]
What is this supposed to be?
image
Will the different bullets be the list of gestures that we support? If so, can we list them in this PR before we merge to main?

**Comment by deborahsrcho** [comment]
> What is this supposed to be? image Will the different bullets be the list of gestures that we support? If so, can we list them in this PR before we merge to main?

Yes, it is supposed to be the list of gestures that we support.

**Comment by Russell-Newton** [comment]
There's inconsistent text coloring on the blue within the demo page. I think we'll want the black text at the top and bottom to also be white.
We'll also need to handle the stuff in #188, but that'll happen after this gets merged

**Review by Russell-Newton — APPROVED** [review]
Looks good!

**Pull request merged**
